[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"

[logging]
level="debug"
use-localtime="true"

[zookeeper]
servers=[ "localhost:2181" ]
timeout=6
root-path="/burrow"

[httpserver.default]
address=":8000"

[client-profile.ConfluentCloudClient]
kafka-version="2.3.0"
client-id="burrow-client"
tls="ConfluentCloudTLS"
sasl="ConfluentCloudSASL"

[tls.ConfluentCloudTLS]
noverify="true"
cafile="/etc/pki/tls/certs/ca-bundle.crt"

[sasl.ConfluentCloudSASL]
username="username"
password="password"
handshake-first="true"

[cluster.ConfluentCloudCluster]
class-name="kafka"
servers="pkc-99999.us-central1.gcp.confluent.cloud:9092"
client-profile="ConfluentCloudClient"
topic-refresh=600
offset-refresh=300

#[consumer.ConfluentCloudConsumer]
#class-name="kafka"
#cluster="ConfluentCloudCluster"
#servers="pkc-99999.us-central1.gcp.confluent.cloud:9092"
#client-profile="ConfluentCloudClient"
#group-blacklist="_confluent*"
#group-whitelist=""
